language: node_js
node_js:
- '0.10'
- '0.12'
sudo: false
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm test
before_deploy:
- npm run archive
deploy:
  provider: releases
  api_key:
    secure: k6ZS1QQ9ftMW0KPEnPNHZ0bfzlqFhiAySEC11HU9QYkBlMTcBC0gb9BlWYRUqH2DFB6igYRTJoZoCdlq00E8ikNI+LUgKNiyIKlG2y6+9tWbACfAXF3FQHzNzQqZF9AFIk7jvnM+q/MLpvk+tS3fYP4wo8Q1Hrn4ZO81wSmqE8m6w3dno1yf7Uc6XnTtO+12naqL+JePVd6lXB/znkExJtf4sj9Qbtg8w7S90UPyo4NhAnhwh0U2wNve+rtchIHbON78cX1rvAm1UCDK5JYrSoHrpwjA35Ea6PQngzfEvrcNHW1KsuqGFZzSxf1hMbruafSRAnBhQz+4p+gTxlggmB2wfhrsL1tS6DjQafgm2ni7gvHRDXIMgFtWUyADM9LF6t2MAW5kSYjtOo7Mir/QuCoMlV/V/STqGouEf55zds5mclU0qaYHQ+VySVAXJRVmy+R2RM4E5foGplRzfKiRxO/R0JHdmL7g4/pK4PirOaLC9iPP0vdszEcb1y+cukBUzrqJhAw8femvX6ITEzNvKNR0+PpJHcHyJKDx0yhJLqy6praX6s30yY8/GoDmq9bD2elKdSL0M73yTw/QnANtrC9Q85we3NPkJV90+77AFvmsJpUI1J887SPukqYlgJrrTrEjRT9wd+fCy7nzFaprnmfzMdToQNytnojjg86abqw=
  file: dist/archive.zip
  skip_cleanup: true
  on:
    repo: chatwork/lambda-sns-to-chatwork-function
    branch: master
    tags: true
